language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.cargo
scala:
  - 2.11.7
jdk:
  - oraclejdk7
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++
      - execstack
before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
script:
  - make clean && make build && make test
