language: scala
sudo: false
cache:
  directories:
    - $HOME/.ivy2
    - $HOME/.cargo
scala:
  - 2.11.7
jdk:
  - oraclejdk8
  - openjdk7
addons:
  apt:
    packages:
      - g++
      - gfortran
      - libblas3gf
      - liblapack3gf
      - execstack
before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
  - export PATH=$HOME/.cargo/bin:$PATH
script:
  - make clean && make build && make test
