[package]
name = "rustjblas"
version = "0.1.0"

[dependencies]
libc = "0.2"
rand = "0.3"

[lib]
crate-type = ["rlib", "dylib", "staticlib"]
name = "rustjblas"
path = "rust/src/lib.rs"

[[bin]]
name = "rustjblas"
path = "rust/src/main.rs"
