[package]
name = "rustjblas"
version = "0.1.0"

[dependencies]
rand = "0.3"

[lib]
crate-type = ["rlib", "dylib"]
name = "rustjblas"
path = "rust/src/lib.rs"

[[bin]]
name = "rustjblas"
path = "rust/src/main.rs"
