/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sadikovi_rustjblas_DoubleMatrix_GPA */

#ifndef _Included_com_github_sadikovi_rustjblas_DoubleMatrix_GPA
#define _Included_com_github_sadikovi_rustjblas_DoubleMatrix_GPA
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
