/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sadikovi_rustjblas_DoubleMatrix_SvdResult */

#ifndef _Included_com_github_sadikovi_rustjblas_DoubleMatrix_SvdResult
#define _Included_com_github_sadikovi_rustjblas_DoubleMatrix_SvdResult
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
