/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_sadikovi_DoubleMatrix */

#ifndef _Included_com_github_sadikovi_DoubleMatrix
#define _Included_com_github_sadikovi_DoubleMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    alloc_new
 * Signature: (II[D)J
 */
JNIEXPORT jlong JNICALL Java_com_github_sadikovi_DoubleMatrix_alloc_1new
  (JNIEnv *, jclass, jint, jint, jdoubleArray);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    alloc_rand
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_github_sadikovi_DoubleMatrix_alloc_1rand
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    alloc_zeros
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_github_sadikovi_DoubleMatrix_alloc_1zeros
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    alloc_ones
 * Signature: (II)J
 */
JNIEXPORT jlong JNICALL Java_com_github_sadikovi_DoubleMatrix_alloc_1ones
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    matrix_rows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_sadikovi_DoubleMatrix_matrix_1rows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    matrix_cols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_com_github_sadikovi_DoubleMatrix_matrix_1cols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    matrix_show
 * Signature: (JZ)V
 */
JNIEXPORT void JNICALL Java_com_github_sadikovi_DoubleMatrix_matrix_1show
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    matrix_tostring
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_github_sadikovi_DoubleMatrix_matrix_1tostring
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_github_sadikovi_DoubleMatrix
 * Method:    matrix_dealloc
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_github_sadikovi_DoubleMatrix_matrix_1dealloc
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
