[package]
name = "rustjblas"
version = "0.1.0"

[dependencies]
libc = "0.2"
rand = "0.3"
nalgebra = "0.13"
blas = "0.19"
openblas-src = "0.5"

[lib]
crate-type = ["staticlib"]
name = "rustjblas"

[dependencies.nalgebra-lapack]
version = "0.5"
default-features = false
features = [ "openblas" ]
